
name: Claude Code CI via Anyrouter Proxy

on:
  issue_comment:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  run_claude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Claude Code via Proxy
        uses: anthropics/claude-code-action@v1
        with:
          prompt: ${{ github.event.comment.body }}
          anthropic_api_key: "DUMMY_KEY"   # 随便填，骗过验证用
        env:
          ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}
          ANTHROPIC_AUTH_TOKEN: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
