# .github/workflows/claude.yml
name: Claude Code CI

on:
  issue_comment:
    types: [created]

jobs:
  run_claude:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Claude Code
      uses: anthropics/claude-code-action@v1
      with:
        prompt: ${{ github.event.comment.body }}
      env:
        ANTHROPIC_BASE_URL: ${{ secrets.ANYROUTER_BASE_URL }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}