# 文件路径：.github/workflows/claude-sonnet-via-proxy.yml
name: Claude Sonnet 4 via Custom Proxy

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Claude Code CLI
        run: npm install -g @anthropic-ai/claude-code

      - name: Run Claude Sonnet 4 via Proxy
        env:
          ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}
          ANTHROPIC_AUTH_TOKEN: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
          ANTHROPIC_LOG: debug
        run: |
          echo "Running Claude Sonnet 4 via proxy..."
          claude --model sonnet --non-interactive > claude-output.md || true
          echo "Output content:"
          cat claude-output.md

      - name: Commit result if changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add claude-output.md
          git commit -m "Update Claude output via proxy" || echo "No changes"
          git push
